// react/src/components/Viewer.jsx
import { useState } from "react";

const Viewer = ({ src, alt, text }) => {
    const [isOpen, setOpen] = useState(false);

    const open = () => {
        setOpen(true);
        window.addEventListener("keydown", keyDown);
    };
    const close = () => {
        setOpen(false);
        window.removeEventListener("keydown", keyDown);
    };
    const keyDown = (e) => {
        if (e.key === "Escape") close();
    };

    return (
        <>
            <img
                src={src}
                alt={alt}
                className="pointer"
                onClick={open}
                aria-hidden="true"
            />

            <div className={"viewer fade " + (isOpen ? "open" : "")}>
                <button className="i-close lg" onClick={close} />
                <img src={src} alt={alt} />
                {text && <div className="mt-6">{text}</div>}
            </div>
        </>
    );
};

export default Viewer;

// svelte/src/lib/Viewer.svelte
<script>
    export let src,
        alt,
        text = "";

    let isOpen = false;

    const open = () => {
        isOpen = true;
        window.addEventListener("keydown", keyDown);
    };
    const close = () => {
        isOpen = false;
        window.removeEventListener("keydown", keyDown);
    };
    const keyDown = (e) => {
        if (e.key === "Escape") close();
    };
</script>

<img {src} {alt} class="pointer" on:click={open} aria-hidden="true" />

<div class="viewer fade" class:open={isOpen}>
    <button class="i-close lg" on:click={close} />
    <img {src} {alt} />
    {#if text}
        <div class="mt-6">{text}</div>
    {/if}
</div>
