// vue/src/components/Viewer.vue
<script setup>
import { ref } from "vue";

defineProps(["src", "alt", "text"]);

let isOpen = ref(false);

const open = () => {
    isOpen.value = true;
    document.addEventListener("keydown", keyDown);
};
const close = () => {
    isOpen.value = false;
    document.removeEventListener("keydown", keyDown);
};
const keyDown = (e) => {
    if (e.key === "Escape") close();
};
</script>

<template>
    <img
        :src="src"
        :alt="alt"
        class="pointer"
        @click="open"
        aria-hidden="true"
    />

    <div class="viewer fade" :class="isOpen && 'open'">
        <button class="i-close lg" @click="close" />
        <img :src="src" :alt="alt" />
        <div class="mt-6" v-if="text">{{ text }}</div>
    </div>
</template>

// svelte/src/lib/Viewer.svelte
<script>
    export let src,
        alt,
        text = "";

    let isOpen = false;

    const open = () => {
        isOpen = true;
        window.addEventListener("keydown", keyDown);
    };
    const close = () => {
        isOpen = false;
        window.removeEventListener("keydown", keyDown);
    };
    const keyDown = (e) => {
        if (e.key === "Escape") close();
    };
</script>

<img {src} {alt} class="pointer" on:click={open} aria-hidden="true" />

<div class="viewer fade" class:open={isOpen}>
    <button class="i-close lg" on:click={close} />
    <img {src} {alt} />
    {#if text}
        <div class="mt-6">{text}</div>
    {/if}
</div>
