// svelte/src/lib/Alert.svelte
<script>
    export let btnText, content;

    let isOpen = false;

    const toggle = () => {
        isOpen = !isOpen;
    };
    const close = () => {
        isOpen = false;
    };
</script>

<button class="btn bg-a" on:click={toggle}>{btnText}</button>

<div class="fade fixed bottom right w-80% max-w-17 m-7" class:open={isOpen}>
    <div class="alert">
        <div>{content}</div>
        <button class="i-close sm" on:click={close} />
    </div>
</div>

// react/src/components/Alert.jsx
import { useState } from "react";

const Alert = ({ btnText, content }) => {
    const [isOpen, setOpen] = useState(false);

    const toggle = () => {
        setOpen(!isOpen);
    };
    const close = () => {
        setOpen(false);
    };

    return (
        <>
            <button className="btn bg-a" onClick={toggle}>
                {btnText}
            </button>

            <div
                className={
                    "fade fixed bottom right w-80% max-w-17 m-7 " +
                    (isOpen ? "open" : "")
                }
            >
                <div className="alert">
                    <div>{content}</div>
                    <button className="i-close sm" onClick={close} />
                </div>
            </div>
        </>
    );
};

export default Alert;
