// svelte/src/lib/Canvas.svelte
<script>
    export let btnText;

    let isOpen = false;

    const open = () => {
        isOpen = true;
        window.addEventListener("keydown", keyDown);
    };
    const close = () => {
        isOpen = false;
        window.removeEventListener("keydown", keyDown);
    };
    const keyDown = (e) => {
        if (e.key === "Escape") close();
    };
</script>

<button class="btn bg-a" on:click={open}>{btnText}</button>

<div class="canvas" class:open={isOpen}>
    <div class="w-80% max-w-17 p-8"><slot /></div>
    <div on:click={close} aria-hidden="true" />
</div>

// react/src/components/Canvas.jsx
import { useState } from "react";

const Canvas = ({ btnText, children }) => {
    const [isOpen, setOpen] = useState(false);

    const open = () => {
        setOpen(true);
        window.addEventListener("keydown", keyDown);
    };
    const close = () => {
        setOpen(false);
        window.removeEventListener("keydown", keyDown);
    };
    const keyDown = (e) => {
        if (e.key === "Escape") close();
    };

    return (
        <>
            <button className="btn bg-a" onClick={open}>
                {btnText}
            </button>

            <div className={"canvas " + (isOpen ? "open" : "")}>
                <div className="w-80% max-w-17 p-8">{children}</div>
                <div onClick={close} aria-hidden="true" />
            </div>
        </>
    );
};

export default Canvas;
