// vue/src/components/Folder.vue
<script setup>
import { ref } from "vue";

defineProps(["title"]);

let isOpen = ref(false);

const toggle = () => {
    isOpen.value = !isOpen.value;
};
</script>

<template>
    <div class="folder" :class="isOpen && 'open'">
        <div @click="toggle" aria-hidden="true">{{ title }}</div>
        <div><slot /></div>
    </div>
</template>

// react/src/components/Folder.jsx
import { useState } from "react";

const Folder = ({ title, children }) => {
    const [isOpen, setOpen] = useState(false);

    const toggle = () => {
        setOpen(!isOpen);
    };

    return (
        <div className={"folder " + (isOpen ? "open" : "")}>
            <div onClick={toggle} aria-hidden="true">
                {title}
            </div>
            <div>{children}</div>
        </div>
    );
};

export default Folder;
